INSERT INTO CATEGORY (ID,DESCRIPTION) VALUES (1001,'E-sports');
INSERT INTO CATEGORY (ID,DESCRIPTION) VALUES (1002,'Sports');
INSERT INTO CATEGORY (ID,DESCRIPTION) VALUES (1003,'Kitchen');


INSERT INTO SUPPLIER (ID, NAME) VALUES (1001,'EA Sports');
INSERT INTO SUPPLIER (ID, NAME) VALUES (1002,'Adidas');
INSERT INTO SUPPLIER (ID, NAME) VALUES (1003,'Penne à 4');


INSERT INTO PRODUCT(ID, NAME, QUANTITYAVAILABLE, FK_SUPPLIER, FK_CATEGORY, CREATED_AT) VALUES (1001,'FIFA', 3, 1001, 1001, CURRENT_TIMESTAMP);

INSERT INTO PRODUCT(ID, NAME, QUANTITYAVAILABLE, FK_SUPPLIER, FK_CATEGORY, CREATED_AT) VALUES (1002,'Soccer', 4, 1002, 1002, CURRENT_TIMESTAMP);

INSERT INTO PRODUCT(ID, NAME, QUANTITYAVAILABLE, FK_SUPPLIER, FK_CATEGORY, CREATED_AT) VALUES (1003,'Cão Véio', 6, 1003, 1003, CURRENT_TIMESTAMP);